# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' sum_perc
#' 
#' @param x Numeric vector
#' @param perc If the percentage of valid (good-quality) values less than `perc`,
#' `NA` returned.
#' 
#' @note `mean_perc` doesn't include the number of invalid values.
#' 
#' @examples
#' x = c(1:8, NA, NA)
#' mean_perc(x)
#' @export
sum_perc <- function(x, perc = 0.8) {
    .Call(`_PhenoAsync_sum_perc`, x, perc)
}

#' @rdname sum_perc
#' @export
mean_perc <- function(x, perc = 0.8) {
    .Call(`_PhenoAsync_mean_perc`, x, perc)
}

